"""empty message

Revision ID: 6e5e9e4303aa
Revises: e73a652e6d9f
Create Date: 2016-08-20 12:04:25.210000

"""

# revision identifiers, used by Alembic.
revision = '6e5e9e4303aa'
down_revision = 'e73a652e6d9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
