"""empty message

Revision ID: 7efd02962380
Revises: f3c071d7872b
Create Date: 2016-08-21 17:11:44.891000

"""

# revision identifiers, used by Alembic.
revision = '7efd02962380'
down_revision = 'f3c071d7872b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('users', 'memeber_since')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('memeber_since', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'member_since')
    ### end Alembic commands ###
