"""empty message

Revision ID: f3c071d7872b
Revises: 3f7d4cc8b977
Create Date: 2016-08-21 17:04:25.603000

"""

# revision identifiers, used by Alembic.
revision = 'f3c071d7872b'
down_revision = '3f7d4cc8b977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('memeber_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('truename', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'truename')
    op.drop_column('users', 'memeber_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
